import type { breachIncident, breachAction } from '@/db/schema';

type Incident = typeof breachIncident.$inferSelect;
type Action = typeof breachAction.$inferSelect;

/**
 * Render the DPB notification draft as Markdown. This is a POC placeholder
 * for the format prescribed by the DPDP Rules 2025 — the final shape will be
 * refined once the Rules notify the exact schema.
 */
export function renderDpbReport(
  incident: Incident,
  actions: ReadonlyArray<Action>,
  cohortCount: number,
): string {
  const lines: string[] = [];
  const fmt = (d: Date | null | undefined) => (d ? d.toISOString() : '—');

  lines.push(`# Notification of Personal Data Breach to the Data Protection Board`);
  lines.push('');
  lines.push(
    `> **NOTE — POC placeholder.** Drafted per the DPDP Act, 2023 (§8(6)) read with`,
    `> the DPDP Rules, 2025. Final format will track the form prescribed once the`,
    `> Rules are notified in full.`,
  );
  lines.push('');
  lines.push(`## 1. Identification`);
  lines.push('');
  lines.push(`- **Incident ID:** \`${incident.id}\``);
  lines.push(`- **Title:** ${incident.title}`);
  lines.push(`- **Severity:** ${incident.severity.toUpperCase()}`);
  lines.push(`- **Current status:** ${incident.status}`);
  lines.push(`- **Detected at:** ${fmt(incident.detectedAt)}`);
  lines.push(`- **Reporting deadline (detected + 72h):** ${fmt(incident.reportingDeadlineAt)}`);
  if (incident.reportedAt) {
    lines.push(`- **Reported to DPB at:** ${fmt(incident.reportedAt)}`);
  }
  lines.push('');
  lines.push(`## 2. Description`);
  lines.push('');
  lines.push(incident.description || '_No description recorded._');
  lines.push('');
  lines.push(`## 3. Affected data principals`);
  lines.push('');
  lines.push(`- **Estimated count:** ${incident.estimatedAffectedCount.toLocaleString('en-IN')}`);
  lines.push(`- **Cohort built:** ${cohortCount.toLocaleString('en-IN')} principal(s)`);
  const cats = incident.affectedDataCategories.length
    ? incident.affectedDataCategories.join(', ')
    : '—';
  lines.push(`- **Data categories affected:** ${cats}`);
  lines.push('');
  lines.push(`## 4. Root cause (preliminary)`);
  lines.push('');
  lines.push(incident.rootCause?.trim() || '_Investigation in progress._');
  lines.push('');
  lines.push(`## 5. Containment & remediation actions taken to date`);
  lines.push('');
  if (actions.length === 0) {
    lines.push('_No actions recorded yet._');
  } else {
    for (const a of actions) {
      lines.push(`- **${fmt(a.createdAt)}** · _${a.kind}_ — ${a.notes}`);
    }
  }
  lines.push('');
  lines.push(`## 6. Notification to data principals`);
  lines.push('');
  lines.push(
    cohortCount > 0
      ? `Cohort of ${cohortCount} principal(s) prepared for direct notification (UI stub — no actual email/SMS gateway in this POC).`
      : `No principal cohort built yet; notification pending.`,
  );
  lines.push('');
  lines.push(`## 7. Contact for the DPB`);
  lines.push('');
  lines.push(`- **Data Protection Officer:** \`dpo@kscb.in\` (placeholder)`);
  lines.push(`- **Submitted by:** Kerala State Cooperative Bank — DPCMS`);
  lines.push('');
  lines.push(`---`);
  lines.push(`_Generated by DPCMS POC at ${new Date().toISOString()}_`);
  return lines.join('\n');
}
